### PR TITLE
Changed to python 3 and added pfind

### PR DESCRIPTION
**Pull request by johnbent**
IO500 needs a parallel find command.  So I added one, pfind, in this awesome pwalk library.  However, for maximum performance on supercomputers, I also updated it to use python 3 so it can use the faster os.scandir module.

### CODE REVIEW

**Comment by guycoates** [comment]
Thanks. I'm on vacation ATM but will look/merge when I get back. Guy

**Comment by johnbent** [comment]
I'm not great at git.  I just added another commit after the original pull request.  If it doesn't get included, I'll do another one if the first one gets merged.

**Comment by johnbent** [comment]
Sorry, accidentally closed.  I told  you I am not great at git.  :)

**Comment by guycoates** [comment]
Hi John,

All merged; the only comment I have is that you might want to add yourself as a author and add any copyright notices you may require to the pfind.py header.

**Comment by guycoates** [comment]
Just realised; if the code has been moved to python3, then the python interpreter should be set to python3 rather than python (PEP 394) in the #! lines.

**Pull request merged**
